version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: tcm/docker/app.Dockerfile
    image: tcm-app:latest
    restart: unless-stopped
    command: []
    env_file:
      - ../.env
    environment:
      TCM_APP_MODE: production
    volumes:
      - ./config:/opt/tcm/tcm/config:ro
      - tcm_app_data:/var/lib/tcm
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
      - /dev/shm:rw,noexec,nosuid,size=32m
    privileged: false
    cap_add:
      - SYS_TIME
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    healthcheck:
      test: [
        "CMD-SHELL",
        "python -c \"import urllib.request,sys; sys.exit(urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=5).status != 200)\"",
      ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

  proxy:
    build:
      context: ..
      dockerfile: tcm/docker/proxy.Dockerfile
    image: tcm-proxy:latest
    restart: unless-stopped
    ports:
      - "443:8443"
    volumes:
      - ./deploy/reverse-proxy/certs:/etc/nginx/certs:ro
      - ./deploy/reverse-proxy/conf.d:/etc/nginx/conf.d:ro
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=16m
      - /var/log/nginx:rw,noexec,nosuid,size=16m
      - /var/run:rw,noexec,nosuid,size=4m
    depends_on:
      app:
        condition: service_healthy
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    healthcheck:
      test: [
        "CMD-SHELL",
        "wget --spider --quiet --tries=1 http://localhost:8080/health || exit 1",
      ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  tcm_app_data:
