version: "3.9"

services:
  app-dev:
    build:
      context: ..
      dockerfile: tcm/docker/app.Dockerfile
    image: tcm-app:latest
    restart: unless-stopped
    command: []
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      TCM_APP_MODE: development
      UVICORN_LOG_LEVEL: debug
    volumes:
      - ./config:/opt/tcm/tcm/config:ro
      - ../tcm/app:/opt/tcm/tcm/app:delegated
      - tcm_app_data:/var/lib/tcm
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
      - /dev/shm:rw,noexec,nosuid,size=32m
    privileged: false
    cap_add:
      - SYS_TIME
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    healthcheck:
      test: [
        "CMD-SHELL",
        "python -c \"import urllib.request,sys; sys.exit(urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=5).status != 200)\"",
      ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  tcm_app_data:
