version: "3.9"

services:
  app-dev:
    build:
      context: ..
      dockerfile: tcm/docker/app.Dockerfile
    image: tcm-app:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      TCM_APP_MODE: development
      UVICORN_LOG_LEVEL: debug
    volumes:
      - ./config:/opt/tcm/tcm/config:ro
      - ../tcm/app:/opt/tcm/tcm/app:delegated
      - tcm_app_data:/var/lib/tcm
#    devices:
#      - /dev/spidev0.0
#      - /dev/spidev0.1
    privileged: false
    cap_add:
      - SYS_TIME
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  tcm_app_data:
